### ISSUE TITLE
Discuss: What makes a good text editor?

### ISSUE THREAD

**Issue by russleyshaw** [russleyshaw/kwiwk#7]
Lots of developers love using [Notepad++](https://notepad-plus-plus.org/) and is a very popular general purpose text editor. [Sublime Text](https://www.sublimetext.com/), [Visual Studio Code](https://code.visualstudio.com/), [Atom](https://atom.io/) also are very popular.

Many developers still enjoy using terminal text editors like [vim](http://www.vim.org/) and [emacs](https://www.gnu.org/software/emacs/) or are required to because they do not have a GUI available (such as people SSH'd into servers).

What features/aspects make a good general purpose text editor for the typical developer?
Also to consider: what features can we not accomplish in a terminal environment?

### Notepad
![image](https://cloud.githubusercontent.com/assets/2314816/22127826/4914ae74-de63-11e6-9b97-2c11955a45d0.png)

### Sublime Text
![image](https://cloud.githubusercontent.com/assets/2314816/22127849/64a0a67a-de63-11e6-9265-f5d41ec359a1.png)

### Visual Studio Code
![image](https://cloud.githubusercontent.com/assets/2314816/22127868/80737224-de63-11e6-9aa0-153d1b7dd8ec.png)

### Vim
![image](https://cloud.githubusercontent.com/assets/2314816/22127890/a09facb6-de63-11e6-9ef7-b5799121f9bc.png)

### Emacs
![image](https://cloud.githubusercontent.com/assets/2314816/22127854/6bdaa166-de63-11e6-833c-4905f6fd62c8.png)

**Comment by russleyshaw** [comment]
# Features
- line numbers

**Comment by 2ajoyce** [comment]
* File access (Opening, Saving, Closing)
* Recently Opened
* Multi-File
* Copy/Paste
* Find and Replace (Supporting Real Expressions)
* Multi-cursor
* Dark/Light Themes
* Google Fonts As Application Fonts?!?!?!?!
* Selection Modifications
     * ToUpper
     * ToLower
     * Sort
     * Split To Lines
* Code Folding
* Bracket Auto-duplication
* Syntax Highlighting
* Auto Indentation
     * Different Number of Spaces
     * Tab vs Spaces

**Comment by russleyshaw** [comment]
> Dark/Light themes

Yes! I was thinking that the themes could be specified by a sort of theme configuration file, and we include a Dark and Light configuration theme files.

> Recently Opened

This would be a nice detail, but I can't remember the last time I used a feature like that in an editor. Maybe others think differently?

> Google Fonts As Application Fonts?!?!?!?!

We won't be able to do this because we will be relying on the console's fonts.

> Multi-cursor

A big feature im hoping we can integrate in.

> Code Folding

This may be less intuitive in a terminal environment since a user wouldnt be able to click the fold icon. We could probably implement it, but I'd be curious how useful it would actually be.

> Auto Indentation

Another big feature im hoping we can implement. We'll want to eventually want to come up with an algorithm for predicting this.

> Copy/Paste

Definitely

> Find and Replace

Definitely

**Comment by 2ajoyce** [comment]
> Recently Opened

This would be a nice detail, but I can't remember the last time I used a feature like that in an editor. Maybe others think differently? 

~ I agree with this, I actually dislike/disable this feature. I put it in since everything seems to include it.

> Google Fonts As Application Fonts?!?!?!?!

We won't be able to do this because we will be relying on the console's fonts.

~ Sad day, I got all excited about that idea. 

> Multi-cursor

A big feature im hoping we can integrate in.

~ This is a must have in any editor I use daily

> Code Folding

This may be less intuitive in a terminal environment since a user wouldnt be able to click the fold icon. We could probably implement it, but I'd be curious how useful it would actually be.

~ That's a really good point. I think I would like to explore the idea rather than trashing it. 

> Auto Indentation

Another big feature im hoping we can implement. We'll want to eventually want to come up with an algorithm for predicting this.

Agreed, this is mandatory imo

> Find and Replace

Definitely

~ Pushing for fancy find and replace with the aforementioned options

**Comment by JeremyDaug** [comment]
Recently opened is a nice feature and I know that I've used it for both personal and company use. It's not required to work, but when you have a lot of projects being able to go between them from the program is very nice.

Everything else is already on my yes list.

**Comment by alzk6** [comment]
I skimmed what people have wrote but having a split screen option would be good... like... being able to put 2 windows side-by-side. Color coding text would be nice too... I don't know what to say because most things have been listed. I'll try to think of more later.
